### ISSUE TITLE
Organizational support

### ISSUE THREAD

**Issue by tonglil** [tonglil/labeler#11]
Apply -or- add-only labels to all repos in an organization via one file.

Whether that file is flat:
```yml
org: github
labels:
  - name: bug
    color: d4c5f9
...
```

Or based on some regex:
```yml
org: github
repos: team-*
  labels:
    - name: bug
      color: d4c5f9
...
```
or
```yml
org: github/team-*
labels:
  - name: bug
    color: d4c5f9
...
```
